In [1]:
import pathlib, sys; sys.path.append(  # noqa: E401, E702
    (pathlib.Path(".").resolve().parent.parent / ".").as_posix()
)

In [2]:
from lib.types.tokenizers import CharacterTokenizer

In [3]:
tokenizer = CharacterTokenizer()

In [4]:
unallowed_second_tokenizer = CharacterTokenizer()

RuntimeError: Class `CharacterTokenizer` may have only 1 instance!

In [5]:
tokenizer.load(
    pathlib.Path("/home/david_tyuman/my_github/dl_dev/character_tokenizer_dict.json")
)

In [6]:
tokenizer.fit("some_path", 100)

ValueError: Tokenizer's already fitted

In [7]:
tokens = tokenizer.encode("hello!")
tokens

[18, 1, 20, 20, 6, 138]

In [8]:
tokenizer.decode(tokens)

'hello!'

In [9]:
s = "asds1201n)ыфвфь!@)B(N))мг0тцс18И(Н.,;И1234567890-+_)(*&^%$#@1234567890_)(;.,:%пиро  N0710212js   'ad"
s == tokenizer.decode(tokenizer.encode(s))

True

In [10]:
tokenizer.encode("���")

[157, 157, 157]

In [11]:
char = tokenizer.decode([987654321123456789])
char

'�'

In [12]:
tokenizer.encode(char)

[157]

In [13]:
tokens = tokenizer.encode("A△▽W")
tokens

[59, -1, -1, 106]

In [14]:
# -1 means unknown token, a token that hasn't been observed while tokenizer training

In [15]:
tokenizer.decode(tokens)

'A��W'

In [16]:
s = "⊲⊳ ⏏ ⌫ ⌧ ⌦ ⍓ ⍌ ⍃ывs"
tokens = tokenizer.encode(s)
tokens

[-1, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 35, 17, 14]

In [17]:
assert (tokenizer.decode(tokenizer.encode(s)) == s) is False

In [18]:
import numpy as np
np.array(tokenizer.encode("hi! bitch!"), dtype=np.int16)

array([ 18,   9, 138,   0,  43,   9,   3,  22,  18, 138], dtype=int16)

In [19]:
import h5py
f_ds = h5py.File(
    "/var/lib/storage/data/benchmarks/machine_translation/wmt/wmt23_ruen/wrangled/char100000tokenized_val_0.h5",
    "r"
)

In [20]:
import random
i = random.randint(0, len(f_ds["input"]) - 1)
inp = f_ds["input"][i]
oup = f_ds["output"][i]
i

795

In [21]:
inp

array([107,   4,   2,  16,  37,   5,  42,   0, 117,   4,  23,   2,  16,
         2,  17,   0,  16,   8,  15,  15,  24,   8,  38,   8,  19,   0,
        54, 101,  38,  17,   4,  15,  13,   5,  34,  25,  54,  28,   0,
        45,  13,   2,   0,   5,  23,   4,  34,   0,  15,   2,  38,  23,
         8,  13,  40,   0,  26,   2,  23,   2,  39,  11,  35,  42,   0,
        16,   4,  42,  13,   5,  11,  37,   0,  17,   2,  38,  11,   5,
        24,  19,   8,   0,  26,   2,  15,  19,   4,   0,   5,  38,  31,
        45,   4,  11,   5,  34,   0,   2,  26,  35,  13,   8,   0,  84,
         8,  49,   5,   2,  11,   8,  19,  40,  11,   2,  37,   2,   0,
         2,  39, 116,   4,  23,   5,  11,   4,  11,   5,  34,   0,   5,
        38,  35,  15,  24,   8,  13,   4,  19,   4,  42,   0,   5,   0,
        26,  16,   2,   4,  24,  13,   5,  16,   2,  17,  58,   5,  24,
         2,  17,   0,  68,  84,  78,  73,  90, 101, 121,  67,  28,   0,
        24,   2,  13,   2,  16,   2,   4,   0,  31,  48,   4,   

In [22]:
oup

array([ 96,   1,   6,  12,  36,   1,   0,  95,   1,  21,   6,  12,   6,
        46,   0,   3,   6,  20,  21,   0,  54,  62,  99,  46,   1,  14,
         3,   9,   7,  54,   0,   3,  18,   7,   3,   0,   3,  18,   1,
         0,   9,  21,   1,   7,   0,   3,   6,   0,  22,  12,   1,   7,
         3,   1,   0,  14,  27,  22,  18,   0,   7,   0,  12,   7,   3,
         9,  10,  36,   0,   7,  12,   6,  14,   1,   0,   7,  30,   3,
         1,  12,   0,   3,  18,   1,   0,  14,   3,  27,  21,  41,   0,
         6,  30,   0,   3,  18,   1,   0,   1,  81,  32,   1,  12,   9,
         1,  10,  22,   1,   0,   6,  30,   0,   3,  18,   1,   0,  83,
         7,   3,   9,   6,  10,   7,  20,   0,  59,  14,  14,   6,  22,
         9,   7,   3,   9,   6,  10,   0,   6,  30,   0,  32,  12,   6,
        14,  32,   1,  22,   3,   6,  12,  14,   0,   7,  10,  21,   0,
        21,   1,  14,   9,  36,  10,   1,  12,  14,   0,  68,  83,  98,
        74,  70,  62, 134,  67,  28,   0,  44,  18,   9,  22,  1

In [23]:
tokenizer.decode(inp)

'Георгий Федоров рассказал "Известиям", что идея создать подобный рейтинг возникла после изучения опыта Национального объединения изыскателей и проектировщиков (НОПРИЗ), которое уже начало работу по созданию специализированного реестра инновационных строительных материалов и реестра импортозамещения строительных материалов.'

In [24]:
tokenizer.decode(oup)

'George Fedorov told "Izvestia" that the idea to create such a rating arose after the study of the experience of the National Association of prospectors and designers (NOPRIZ), which has already begun work on the creation of a dedicated inventory of innovative building materials and a register of import replacement of building materials.'

In [25]:
assert tokenizer.encode(tokenizer.decode(inp)) == inp.tolist()
assert tokenizer.encode(tokenizer.decode(oup)) == oup.tolist()

In [26]:
i = random.randint(0, len(f_ds["input"]) - 1)
inp = f_ds["input"][i]
oup = f_ds["output"][i]
i

28

In [27]:
inp

array([73,  2, 71, 13,  2, 25, 31,  0, 15, 26,  4, 49,  5,  8, 19,  5, 15,
       13, 35,  0,  5, 15, 24,  8, 19,  5,  0, 15, 26,  2, 15,  2, 39, 35,
       28,  0, 24,  8, 24,  0, 39, 35, 15, 13, 16,  2,  0, 17,  2, 15, 15,
       13,  8, 11,  2, 17,  5, 13, 40,  0, 24,  2, 48, 31,  0,  5,  0, 11,
        4,  0, 23,  2, 26, 31, 15, 13,  5, 13, 40,  0, 16, 31, 39, 49,  4,
       17,  8, 11,  5, 34, 33], dtype=int16)

In [28]:
oup

array([60, 18,  1, 12,  1, 30,  6, 12,  1, 28,  0,  3, 18,  1,  0, 14, 32,
        1, 22,  9,  7, 20,  9, 14,  3, 14,  0, 44,  1, 12,  1,  0, 20,  6,
        6, 55,  9, 10, 36,  0, 30,  6, 12,  0, 44,  7, 41, 14,  0,  3,  6,
        0, 97, 27,  9, 22, 55, 20, 41,  0, 12,  1, 14,  3,  6, 12,  1,  0,
        3, 18,  1,  0, 14, 55,  9, 10,  0,  7, 10, 21,  0,  7, 46,  6,  9,
       21,  0, 22, 18,  6, 32, 32,  9, 10, 36, 33], dtype=int16)

In [29]:
tokenizer.decode(inp)

'Поэтому специалисты искали способы, как быстро восстановить кожу и не допустить рубцевания.'

In [30]:
tokenizer.decode(oup)

'Therefore, the specialists were looking for ways to quickly restore the skin and avoid chopping.'

In [31]:
assert tokenizer.encode(tokenizer.decode(inp)) == inp.tolist()
assert tokenizer.encode(tokenizer.decode(oup)) == oup.tolist()

In [32]:
f_ds.close()